title: Game development blog
author: Pere Viader Masuet
email: pere.viader22@gmail.com

# Write an awesome description for your new site here. You can edit this
# line in _config.yml. It will appear in your document head meta (for
# Google search results) and in your feed.xml site description.
description: > # this means to ignore newlines until "show_exerpts:"
  Projects, thoughts and opinions from a game developer  

show_excerpts: true # set to true to show excerpts on the homepage

# Minima date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
sass:
  sass_dir: _sass

permalink: /posts/:title/
texture:
  title: Pere Viader Masuet
  tagline: Game Developer
  date_format: "%b %-d, %Y"
  style: black
  showNav: false
  showPicker: false
  disqus_shortname: game-developer-blog

  # generate social links in footer
  social_links:
    twitter: truci4
    github:  PereViader
    linkedIn: in/pere-viader-masuet
    rss: feed.xml
 

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
#header_pages:
# - about.md

# Build settings
# theme: texture

plugins:
  - jekyll-seo-tag
  - jekyll-feed

exclude:
  - excluded 

google_analytics: UA-158047735-1